### ISSUE TITLE
No license listed 

### ISSUE THREAD

**Issue by Vixxd** [Rogue85/unity-characterselection#1]
Hi there,

I absolutely love this - I am just wondering which license you are providing it with? I would love to use it but can't find any information about which license you are distributing it under (e.g. BSD, MIT, ...) https://help.github.com/articles/open-source-licensing/

Thanks in advance :)

**Comment by Rogue85** [comment]
Fixed! Sorry for the inconvenience :)

**Comment by Vixxd** [comment]
Thanks so much! I'll let you know how we use it and credit :)
